### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by chestamittal**

### CODE REVIEW

**Comment by rishabh-997** [comment]
ruk jao bemta mittal, ye repo eligible nhi hai

**Comment by chestamittal** [comment]
kaahe?

**Comment by rishabh-997** [comment]
repo par label nahi laga hai

**Comment by chestamittal** [comment]
to wese kese lagta hai?

**Review by SarthakSahu1009 — APPROVED** [review]
bahut acha

**Pull request merged**
